### ISSUE TITLE
Parse Set Up

### ISSUE THREAD

**Issue by cookiewho** [Fitness-App-Gang/Quick-Fitness#1]
- [x] Set up parse server
   - [x] Muscle Model
      - [x] Exercise Model
   - [x] User Model
   - [x] Post Model

**Comment by codepathreview** [comment]
Looks like you did not implement the following user story/ies:

- Wireframe images (+3pts)

We encourage everyone to complete all the [required user stories](https://courses.codepath.org/snippets/android_university/grading) for each assignment to demonstrate topic understanding. While we **won't** be regrading this submission anymore, we hope you try to complete all required user stories [indicated here](https://courses.codepath.org/snippets/android_university/grading) or on the Course Portal assignment tab for **future assignments**. 
/cc @codepathreview

**Comment by ChristopherCautivar** [comment]
I'll take this issue
